### PR TITLE
upgraded packages

### PR DESCRIPTION
**Pull request by jasonvillalon**
upgrade react 16@latest
upgrade react-router@latest
upgrade redux-router-redux@next
etc..

### CODE REVIEW

**Comment by altaywtf** [comment]
hello @jasonvillalon, thank you so much for the effort!
could you please make sure project builds as expected?

**Comment by jasonvillalon** [comment]
yes. i will try to fix the tests tom.

**Comment by altaywtf** [comment]
@jasonvillalon thank you!

**Comment by jasonvillalon** [comment]
@altayaydemir im not sure how to make the tests work. when running test on each .test files, react component is not enclosed within Router.

**Pull request closed without merging**
